modmap:
  - name: Colemak DH
    remap:
      KEY_E: KEY_F
      KEY_R: KEY_P
      KEY_T: KEY_B
      KEY_Y: KEY_J
      KEY_U: KEY_L
      KEY_I: KEY_U
      KEY_O: KEY_Y
      KEY_P: KEY_SEMICOLON
      KEY_S: KEY_R
      KEY_D: KEY_S
      KEY_F: KEY_T
      KEY_H: KEY_M
      KEY_J: KEY_N
      KEY_K: KEY_E
      KEY_L: KEY_I
      KEY_SEMICOLON: KEY_O
      KEY_Z: KEY_X
      KEY_X: KEY_C
      KEY_C: KEY_D
      KEY_V: KEY_V
      KEY_B: KEY_Z
      KEY_N: KEY_K
      KEY_M: KEY_H
  - name: Additionals
    remap:
      KEY_CAPSLOCK: KEY_ESC
      KEY_ESC: KEY_GRAVE
keymap:
  - name: VIM
    remap:
      M-n: left
      M-e: down
      M-i: up
      M-o: right
